name: Deploy to Vercel (Production)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest

      - name: Descargar configuración de entorno de Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Construir el proyecto
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Desplegar a Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
